### ISSUE TITLE
KeyError: 'payload'

### ISSUE THREAD

**Issue by vuducdong** [DaveOff/NordLynx#2]
That's error , can't running nordlynx.py

-----  NordLynx Configuration File  -----

Traceback (most recent call last):
  File "C:\Users\vuduc\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 450, in _on_message
    callback(message, data)
  File "C:\NordLynx-main\nordlynx.py", line 40, in onMessage
    if 'PrivateKey' not in message["payload"]: return
KeyError: 'payload'
[+] Select a server

@DaveOff  can you fix this error? Thanks!

**Comment by LitenBuzzTh** [comment]
I get the same error here. 

and installed all requirements 

running on python 3.7

**Comment by hmdrza01** [comment]
same here

**Comment by vuducdong** [comment]
> I get the same error here.
> 
> and installed all requirements
> 
> running on python 3.7

I tried all version, with all Windows OS (Win10, Win11).

Only the previous win10 computer that I installed and run, without changing anything, not updating, or doing anything, it still works.

On another computer, I tried to do the same thing on that PC, but I get the same error as above. It's hard to understand.

**Comment by kankees** [comment]
I found a solution to solve this problem you need to copy 'nordlynx.py' to python install directory then run with cmd admin 'python nordlynx.py'
and don't forget create a new folder name 'profile' on the same directory

**Comment by vuducdong** [comment]
> I found a solution to solve this problem you need to copy 'nordlynx.py' to python install directory then run with cmd admin 'python nordlynx.py' and don't forget create a new folder name 'profile' on the same directory

ok, I tried it and still the same error, not fixed yet .

**Comment by kratos122-cell** [comment]
Same issue..
